access_token = "dbfce0f8-ceda-4673-bbaf-f18d74cd59f7"
device_id = "3cdffe2e-869c-4ea2-a38c-a0a06e3ecab8"
license_key = "BR124Fv3-69bza0I3-9v5j12lV"
private_key = "KODK0pJqmd0EessQt6KrXcGJo7gbuRGElv8yXLHdelQ="
