#!/usr/bin/env bash

# make applications use ibus
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT4_IM_MODULE=ibus
export CLUTTER_IM_MODULE=ibus

# NetworkManager is the most popular way to manage wireless networks on Linux,
# and nm-applet is a desktop environment-independent system tray GUI for it.
nm-applet > /dev/null 2>&1 &

# keep chrome logins
/usr/bin/gnome-keyring-daemon --start --components=secrets &

# ibus
ibus-daemon --xim -d -r

# wallpaper
~/.fehbg

# window compositor
picom -b > /dev/null 2>&1 &

# nightlight
redshift > /dev/null 2>&1 &

# flash focused window
flashfocus &

# map short-pressed Caps to esc
xcape -t 170
