#!/usr/bin/env bash

# NetworkManager is the most popular way to manage wireless networks on Linux,
# and nm-applet is a desktop environment-independent system tray GUI for it.
nm-applet > /dev/null 2>&1 &

# keep chrome logins
/usr/bin/gnome-keyring-daemon --start --components=secrets &

# ibus
ibus-daemon --xim -d -r

# wallpaper
~/.fehbg

# window compositor
picom -b

# nightlight
redshift > /dev/null 2>&1 &

# flash focused window
flashfocus &

# map short-pressed Caps to esc, long-pressed Caps to Ctrl
setxkbmap us -option ctrl:nocaps
xcape -t 170
